version: "3"

services:
  app:
    build: images/nginx
    env_file: env/docker.env
    ports:
      - "80:8000"
      - "443:8443"
    links:
      - db
      - phpfpm
    volumes: &appvolumes
      - appdata:/var/www/html
      - sockdata:/sock
      - ssldata:/etc/nginx/certs

  phpfpm:
    build: images/php/${PHP_VERSION}
    env_file: env/docker.env
    links:
      - db
    volumes: *appvolumes
    extra_hosts:
      - host.docker.internal:host-gateway

  db:
    image: percona:5.7
    command: --max_allowed_packet=64M
    ports:
      - "3306:3306"
    env_file: 
      - env/db.env
      - env/docker.env
    volumes:
      - dbdata:/var/lib/mysql

  phpmyadmin:
    build: images/phpmyadmin
    env_file:
      - env/db.env
      - env/docker.env
    ports:
      - 8080:80

  ## Disabling cron by default as it uses higher CPU, enable if needed
  #cron:
  #  image: markoshust/magento-php:7.4-fpm-6
  #  user: root
  #  command: /usr/local/bin/cronstart
  #  tty: true
  #  links:
  #    - db
  #  volumes: *appvolumes

volumes:
  appdata:
  dbdata:
  sockdata:
  ssldata:
